### ISSUE TITLE
composite: images do not have same numbers of bands (Vips::Error)

### ISSUE THREAD

**Issue by yshmarov** [igor-alexandrov/jekyll-og-image#2]
it works with a `.jpg`, `.jpeg`, but now thi a `.png`:

```diff
-  image: "/assets/static-pages/yaro-avatar.png"
+  image: "/assets/static-pages/yaro-cindy.jpg"
```

**Comment by igor-alexandrov** [comment]
What version of `libvips` do you have? I used `.png` image and everything was good.

**Comment by yshmarov** [comment]
`ruby-vips (2.2.0)`

**Comment by StanBoyet** [comment]
I'm encountering the same issue, with `ruby-vips (2.2.2)` @igor-alexandrov

**Comment by igor-alexandrov** [comment]
I will look at this during the weekend.
