### ISSUE TITLE
silence Jekyll Og Image: Skipping image generation

### ISSUE THREAD

**Issue by yshmarov** [igor-alexandrov/jekyll-og-image#4]
it would be cool to have a way to silence these notifications. they do not look very valuable
<img width="1710" alt="Screenshot 2024-02-09 at 19 55 47" src="https://github.com/igor-alexandrov/jekyll-og-image/assets/13472945/40f67d9e-b4a1-4cc1-b245-90c49c12e6ae">

**Comment by igor-alexandrov** [comment]
Sure, will do!

**Comment by igor-alexandrov** [comment]
Added `verbose` setting with default `false`. Please upgrade to 1.3.0

**Comment by yshmarov** [comment]
Works. Thanks!
